### PR TITLE
Flow type annotations support

### PR DESCRIPTION
**Pull request by gabriel-laet**
Including Flow type annotations keys. 

Thanks to `esprima-fb` [recent](https://github.com/facebook/esprima/pull/70) support of types on AST, it's possible to traverse through code using JSX Harmony + Flow annotations.

Still need to improve tests (not covering all keys yet) and maybe think in a better way to test JSX and Type Annotations separately. Looking forward for your thoughts.

### CODE REVIEW

**Comment by RReverser** [comment]
Great, thanks!

**Comment by RReverser** [comment]
@gabriel-laet Could you please fix indentations so all the files are formatted with tabs and not mixed and then squash it to one commit?

**Comment by gabriel-laet** [comment]
Done. Using tabs and not spaces, squashed in one commit.

**Comment by RReverser** [comment]
Thanks! This is awesome!

**Pull request merged**
